### ISSUE TITLE
Docker compose - sys.stderr.write(f"ERROR: {exc}") : invalid syntax

### ISSUE THREAD

**Issue by johhnry** [cgwire/cgwire#23]
Hi,

### Steps to reproduce

I did the following steps on a CentOS Linux 8 x86_64 : 

```bash
$ git clone https://github.com/cgwire/cgwire
$ cd cgwire/compose
$ docker-compose up -d
```

### Issue

and I have the following error at step `17/34` :

```
Step 17/34 : RUN python3 -m venv /opt/zou/env &&     /opt/zou/env/bin/pip install --upgrade pip setuptools wheel &&     /opt/zou/env/bin/pip install zou==${ZOU_VERSION} &&     rm -rf /root/.cache/pip/
 ---> Running in ea16e8bf127b
Collecting pip
  Downloading https://files.pythonhosted.org/packages/cd/82/04e9aaf603fdbaecb4323b9e723f13c92c245f6ab2902195c53987848c78/pip-21.1.2-py3-none-any.whl (1.5MB)
Collecting setuptools
  Downloading https://files.pythonhosted.org/packages/4e/78/56aa1b5f4d8ac548755ae767d84f0be54fdd9d404197a3d9e4659d272348/setuptools-57.0.0-py3-none-any.whl (821kB)
Collecting wheel
  Downloading https://files.pythonhosted.org/packages/65/63/39d04c74222770ed1589c0eaba06c05891801219272420b40311cd60c880/wheel-0.36.2-py2.py3-none-any.whl
Installing collected packages: pip, setuptools, wheel
  Found existing installation: pip 8.1.1
    Uninstalling pip-8.1.1:
      Successfully uninstalled pip-8.1.1
  Found existing installation: setuptools 20.7.0
    Uninstalling setuptools-20.7.0:
      Successfully uninstalled setuptools-20.7.0
Successfully installed pip-21.1.2 setuptools-57.0.0 wheel-0.36.2
Traceback (most recent call last):
  File "/opt/zou/env/bin/pip", line 7, in <module>
    from pip._internal.cli.main import main
  File "/opt/zou/env/lib/python3.5/site-packages/pip/_internal/cli/main.py", line 58
    sys.stderr.write(f"ERROR: {exc}")
                                   ^
SyntaxError: invalid syntax
The command '/bin/sh -c python3 -m venv /opt/zou/env &&     /opt/zou/env/bin/pip install --upgrade pip setuptools wheel &&     /opt/zou/env/bin/pip install zou==${ZOU_VERSION} &&     rm -rf /root/.cache/pip/' returned a non-zero code: 1
ERROR: Service 'cgwire' failed to build : Build failed 
```

Seems related to the fact that pip dropped support for python 2 and 3.5 (in this case) : https://stackoverflow.com/questions/66212924/pip-sys-stderr-writeferror-exc-with-python-3-5

I don't really know how to solve that : the ubuntu 16.04 base image install python3.5 with `apt`? It's also mentionned that python2 is needed for supervisord in the Dockerfile (I also saw the usage of `tini` so what's the link between the two?)

Thanks again for making this open source!

### Versions : 

- cgwire : commit d2a30e36a2c6634c34e412429ffc4767415a82eb
- OS : `CentOS Linux 8 x86_64`
- Docker : `Docker version 20.10.6, build 370c289`
- docker-compose : `docker-compose version 1.29.2, build 5becea4c`

**Comment by nledez** [comment]
Nous avons supprimé le fichier docker compose.
