### ISSUE TITLE
Init db and data when building the docker image

### ISSUE THREAD

**Issue by g-LuL** [cgwire/cgwire#5]
Hi
When i build the docker image, the database initialization does not complete. I guess it occurs when the zou script (init_db,is launched.
An exception is raised : 

```
Traceback (most recent call last):
  File "/opt/zou/env/bin/zou", line 11, in <module>
    load_entry_point('zou==0.3.9', 'console_scripts', 'zou')()
  File "/opt/zou/env/lib/python3.5/site-packages/click/core.py", line 722, in __call__
    return self.main(*args, **kwargs)
  File "/opt/zou/env/lib/python3.5/site-packages/click/core.py", line 676, in main
    _verify_python3_env()
  File "/opt/zou/env/lib/python3.5/site-packages/click/_unicodefun.py", line 118, in _verify_python3_env
    'for mitigation steps.' + extra)
RuntimeError: Click will abort further execution because Python 3 was configured to use ASCII as encoding for the environment.  Consult http://click.pocoo.org/python3/for mitigation steps.

This system supports the C.UTF-8 locale which is recommended.
You might be able to resolve your issue by exporting the
following environment variables:

    export LC_ALL=C.UTF-8
    export LANG=C.UTF-8
```

**Comment by frankrousseau** [comment]
Thank you @g-LuL for reporting! We changed the packaging recently. It may be linked.

**Comment by frankrousseau** [comment]
Hello @g-LuL,

  It should be fixed. Could you try again?

**Comment by g-LuL** [comment]
Hi @frankrousseau 
I confirm, it's fixed.
Thanks
