### ISSUE TITLE
Docker build errors

### ISSUE THREAD

**Issue by g-LuL** [cgwire/cgwire#9]
Hi !
I've noticed errors during docker build since 0.4.6 or 0.4.7.
Errors occured when executing `zou` (`zou init_db` `zou init_data` and `zou create_admin`)
Here's the log :
```
Traceback (most recent call last):
  File "/opt/zou/env/bin/zou", line 11, in <module>
    load_entry_point('zou==0.4.7', 'console_scripts', 'zou')()
  File "/opt/zou/env/lib/python3.5/site-packages/click/core.py", line 722, in __call__
    return self.main(*args, **kwargs)
  File "/opt/zou/env/lib/python3.5/site-packages/click/core.py", line 676, in main
    _verify_python3_env()
  File "/opt/zou/env/lib/python3.5/site-packages/click/_unicodefun.py", line 118, in _verify_python3_env
    'for mitigation steps.' + extra)
RuntimeError: Click will abort further execution because Python 3 was configured to use ASCII as encoding for the environment.  Consult http://click.pocoo.org/python3/for mitigation steps.

This system supports the C.UTF-8 locale which is recommended.
You might be able to resolve your issue by exporting the
following environment variables:

    export LC_ALL=C.UTF-8
    export LANG=C.UTF-8
```

**Comment by frankrousseau** [comment]
Thanks for reporting. We should find a way to perform these exports automatically.

**Comment by g-LuL** [comment]
I'm not sure about this issue.
Let me double check my build process. I've discovered I've used an old git repository to build.

**Comment by g-LuL** [comment]
Sorry about the noise :(
My mistake, my git repository was too old.
The build process is doing fine.

**Comment by frankrousseau** [comment]
Thats a good news :) !
